import { MCPGuard } from '@mcp-guard/core';
import type { MCPServerConfig, ScanResult } from '@mcp-guard/core';

export interface GenerateReportArgs {
  config: MCPServerConfig;
  format?: 'json' | 'markdown' | 'html' | 'sarif' | 'pdf';
  includeRemediation?: boolean;
  includeCompliance?: boolean;
}

export class GenerateReportTool {
  private mcpGuard: MCPGuard;

  constructor() {
    this.mcpGuard = new MCPGuard();
  }

  async execute(args: GenerateReportArgs): Promise<string> {
    const { 
      config, 
      format = 'json',
      includeRemediation = true,
      includeCompliance = false 
    } = args;
    
    // Run comprehensive scan
    const result = await this.mcpGuard.scan(
      { default: config },
      { includeCompliance }
    );

    // Generate report based on format
    switch (format) {
      case 'json':
        return this.generateJSON(result);
      case 'markdown':
        return this.generateMarkdown(result, includeRemediation);
      case 'html':
        return this.generateHTML(result, includeRemediation);
      case 'sarif':
        return this.generateSARIF(result);
      case 'pdf':
        return this.generatePDFContent(result, includeRemediation);
      default:
        throw new Error(`Unsupported format: ${format}`);
    }
  }

  private generateJSON(result: ScanResult): string {
    return JSON.stringify(result, null, 2);
  }

  private generateMarkdown(result: ScanResult, includeRemediation: boolean): string {
    const lines: string[] = [
      '# MCP-Guard Security Report',
      '',
      `**Generated:** ${new Date().toISOString()}`,
      `**Version:** 1.0.0`,
      '',
      '## Executive Summary',
      '',
      `- **Security Score:** ${result.summary.score}/100 (${result.summary.grade})`,
      `- **Total Vulnerabilities:** ${result.summary.vulnerabilitiesFound}`,
      `- **Critical Issues:** ${result.summary.critical}`,
      `- **High Risk Issues:** ${result.summary.high}`,
      `- **Medium Risk Issues:** ${result.summary.medium}`,
      `- **Low Risk Issues:** ${result.summary.low}`,
      ''
    ];

    if (result.vulnerabilities.length > 0) {
      lines.push('## Vulnerabilities');
      lines.push('');
      
      // Group by severity
      const bySeverity: Record<string, typeof result.vulnerabilities> = {};
      result.vulnerabilities.forEach(vuln => {
        if (!bySeverity[vuln.severity]) {
          bySeverity[vuln.severity] = [];
        }
        bySeverity[vuln.severity].push(vuln);
      });

      ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW'].forEach(severity => {
        if (bySeverity[severity]) {
          lines.push(`### ${severity} Severity`);
          lines.push('');
          
          bySeverity[severity].forEach((vuln, index) => {
            lines.push(`#### ${index + 1}. ${vuln.title}`);
            lines.push('');
            lines.push(`- **Type:** ${vuln.type}`);
            lines.push(`- **Location:** ${vuln.server}`);
            lines.push(`- **Description:** ${vuln.description}`);
            
            if (includeRemediation && vuln.remediation) {
              lines.push('');
              lines.push('**Remediation:**');
              vuln.remediation.steps.forEach(step => {
                lines.push(`1. ${step}`);
              });
              if (vuln.remediation.automated) {
                lines.push('');
                lines.push('> ✅ Automated fix available');
              }
            }
            lines.push('');
          });
        }
      });
    }

    if (result.recommendations.length > 0) {
      lines.push('## Recommendations');
      lines.push('');
      result.recommendations.forEach((rec, index) => {
        lines.push(`${index + 1}. ${rec}`);
      });
      lines.push('');
    }

    lines.push('## Scan Details');
    lines.push('');
    lines.push('| Metric | Value |');
    lines.push('|--------|-------|');
    lines.push(`| Scan Date | ${new Date().toLocaleDateString()} |`);
    lines.push(`| Scan Time | ${new Date().toLocaleTimeString()} |`);
    lines.push(`| Scanner Version | 1.0.0 |`);
    lines.push(`| Total Checks | ${result.vulnerabilities.length + 50} |`);
    lines.push('');
    
    lines.push('---');
    lines.push('*Report generated by MCP-Guard Security Scanner*');

    return lines.join('\n');
  }

  private generateHTML(result: ScanResult, includeRemediation: boolean): string {
    const severityColors = {
      CRITICAL: '#dc2626',
      HIGH: '#ea580c',
      MEDIUM: '#ca8a04',
      LOW: '#16a34a'
    };

    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MCP-Guard Security Report</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background: #f5f5f5;
        }
        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            border-radius: 10px;
            margin-bottom: 30px;
        }
        .summary {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            margin-bottom: 30px;
        }
        .stat-card {
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        .stat-value {
            font-size: 2em;
            font-weight: bold;
            color: #667eea;
        }
        .vulnerability {
            background: white;
            padding: 20px;
            margin-bottom: 20px;
            border-radius: 8px;
            border-left: 4px solid;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        .severity-CRITICAL { border-left-color: ${severityColors.CRITICAL}; }
        .severity-HIGH { border-left-color: ${severityColors.HIGH}; }
        .severity-MEDIUM { border-left-color: ${severityColors.MEDIUM}; }
        .severity-LOW { border-left-color: ${severityColors.LOW}; }
        .badge {
            display: inline-block;
            padding: 4px 8px;
            border-radius: 4px;
            font-size: 0.85em;
            font-weight: bold;
            color: white;
        }
        .remediation {
            background: #f0f9ff;
            padding: 15px;
            border-radius: 6px;
            margin-top: 15px;
        }
        .grade {
            font-size: 3em;
            font-weight: bold;
            text-align: center;
            padding: 20px;
            background: white;
            border-radius: 50%;
            width: 100px;
            height: 100px;
            display: flex;
            align-items: center;
            justify-content: center;
            margin: 0 auto;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>🛡️ MCP-Guard Security Report</h1>
        <p>Generated: ${new Date().toISOString()}</p>
    </div>

    <div class="summary">
        <div class="stat-card">
            <div class="grade">${result.summary.grade}</div>
            <p style="text-align: center; margin-top: 10px;">Security Grade</p>
        </div>
        <div class="stat-card">
            <div class="stat-value">${result.summary.score}/100</div>
            <p>Security Score</p>
        </div>
        <div class="stat-card">
            <div class="stat-value">${result.summary.vulnerabilitiesFound}</div>
            <p>Total Vulnerabilities</p>
        </div>
        <div class="stat-card">
            <div class="stat-value" style="color: ${severityColors.CRITICAL}">${result.summary.critical}</div>
            <p>Critical Issues</p>
        </div>
    </div>

    <h2>Vulnerabilities</h2>
    ${result.vulnerabilities.map(vuln => `
        <div class="vulnerability severity-${vuln.severity}">
            <h3>${vuln.title} <span class="badge" style="background: ${severityColors[vuln.severity as keyof typeof severityColors]}">${vuln.severity}</span></h3>
            <p><strong>Type:</strong> ${vuln.type}</p>
            <p><strong>Location:</strong> <code>${vuln.server}</code></p>
            <p>${vuln.description}</p>
            ${includeRemediation && vuln.remediation ? `
                <div class="remediation">
                    <h4>Remediation Steps:</h4>
                    <ol>
                        ${vuln.remediation.steps.map(step => `<li>${step}</li>`).join('')}
                    </ol>
                    ${vuln.remediation.automated ? '<p>✅ Automated fix available</p>' : ''}
                </div>
            ` : ''}
        </div>
    `).join('')}

    ${result.recommendations.length > 0 ? `
        <h2>Recommendations</h2>
        <div style="background: white; padding: 20px; border-radius: 8px;">
            <ol>
                ${result.recommendations.map(rec => `<li>${rec}</li>`).join('')}
            </ol>
        </div>
    ` : ''}

    <footer style="margin-top: 50px; text-align: center; color: #666;">
        <p>Report generated by MCP-Guard Security Scanner v1.0.0</p>
    </footer>
</body>
</html>`;
  }

  private generateSARIF(result: ScanResult): string {
    const sarif = {
      version: '2.1.0',
      $schema: 'https://schemastore.azurewebsites.net/schemas/json/sarif-2.1.0.json',
      runs: [{
        tool: {
          driver: {
            name: 'MCP-Guard',
            version: '1.0.0',
            informationUri: 'https://github.com/mcp-guard',
            rules: result.vulnerabilities.map(vuln => ({
              id: vuln.id,
              name: vuln.title,
              shortDescription: {
                text: vuln.description
              },
              fullDescription: {
                text: vuln.description
              },
              helpUri: `https://mcp-guard.dev/vulnerabilities/${vuln.type}`,
              defaultConfiguration: {
                level: this.severityToSarifLevel(vuln.severity)
              }
            }))
          }
        },
        results: result.vulnerabilities.map(vuln => ({
          ruleId: vuln.id,
          level: this.severityToSarifLevel(vuln.severity),
          message: {
            text: vuln.description
          },
          locations: [{
            physicalLocation: {
              artifactLocation: {
                uri: vuln.server
              }
            }
          }],
          fixes: vuln.remediation ? [{
            description: {
              text: vuln.remediation.steps.join('; ')
            }
          }] : undefined
        }))
      }]
    };

    return JSON.stringify(sarif, null, 2);
  }

  private severityToSarifLevel(severity: string): string {
    switch (severity) {
      case 'CRITICAL':
      case 'HIGH':
        return 'error';
      case 'MEDIUM':
        return 'warning';
      case 'LOW':
        return 'note';
      default:
        return 'none';
    }
  }

  private generatePDFContent(result: ScanResult, includeRemediation: boolean): string {
    // Return a structured format that can be converted to PDF
    // In production, this would use a PDF library like pdfkit or puppeteer
    return JSON.stringify({
      format: 'pdf',
      title: 'MCP-Guard Security Report',
      metadata: {
        author: 'MCP-Guard',
        subject: 'Security Vulnerability Report',
        keywords: 'security, vulnerabilities, mcp, scanning',
        creator: 'MCP-Guard v1.0.0',
        producer: 'MCP-Guard PDF Generator',
        creationDate: new Date().toISOString()
      },
      content: {
        summary: result.summary,
        vulnerabilities: result.vulnerabilities,
        recommendations: result.recommendations,
        includeRemediation
      },
      styling: {
        font: 'Helvetica',
        fontSize: 12,
        lineHeight: 1.5,
        margins: { top: 72, bottom: 72, left: 72, right: 72 }
      }
    }, null, 2);
  }
}

export const generateReportTool = new GenerateReportTool();